# checkoutLocation: src/github.com/skareeg/hexentropy
# workspaceLocation: /
image: gitpod/workspace-full-vnc
ports:
  - port: 6080
    protocol: "http"
tasks:
  - name: Environment Dependencies Setup
    init: sudo apt update && sudo apt install -y g++ pkg-config libx11-dev libasound2-dev libudev-dev
vscode:
  extensions:
    - rust-lang.rust-analyzer